CREATE DATABASE IF NOT EXIST DVD;

USE DVD;

CREATE TABLE IF NOT EXIST CLIENTS (
    Code_client INT AUTO_INCREMENT PRIMARY KEY 
    Titre VARCHAR (50) NOT NULL,
    Prenom VARCHAR (25) NOT NULL,
    Nom VARCHAR (25) NOT NULL,
    Adresse_rue VARCHAR (40) NOT NULL,
    Code_postal INT (10) NOT NULL,
    Ville VARCHAR (40) NOT NULL,
    Num_telephone INT (15) NOT NULL,
    Date_naissance INT (10) NOT NULL,
    Enfants VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXIST TYPES_LOCATIONS (
    Code_type INT AUTO_INCREMENT PRIMARY KEY,
    Libelle VARCHAR (15) NOT NULL,
    Coefficient FLOAT (15) NOT NULL,
    Nb_jours INT (50) NOT NULL
);

CREATE TABLE IF NOT EXIST REALISATEURS (
    Code_realisateur INT AUTO_INCREMENT PRIMARY KEY,
    Prenom VARCHAR (30) NOT NULL,
    Nom VARCHAR (30) NOT NULL,
    Annee_naissance INT (10) NOT NULL,
    Pays VARCHAR (15) NOT NULL
);

CREATE TABLE IF NOT EXIST GENRES_film (
    Code_genre INT AUTO_INCREMENT PRIMARY KEY,
    signification VARCHAR (50) NOT NULL
);

CREATE TABLE IF NOT EXIST FACTURES (
    Num_facture INT AUTO_INCREMENT PRIMARY KEY
    Code_client INT AUTO_INCREMENT,
    Date_facture INT AUTO_INCREMENT
);

CREATE TABLE IF NOT EXIST DVD (
    Num_dvd INT AUTO_INCREMENT PRIMARY KEY,
    Titre VARCHAR (40) NOT NULL,
    Prix_base INT (5) NOT NULL,
    Code_realisateur INT AUTO_INCREMENT,
    Code_genre INT AUTO_INCREMENT,
    Annee INT (5) NOT NULL,
    Descriptif VARCHAR (200) NOT NULL,
    Duree INT (5) NOT NULL
);

CREATE TABLE IF NOT EXIST LOCATIONS (
    Num_facture INT AUTO_INCREMENT PRIMARY KEY,
    Num_dvd INT AUTO_INCREMENT,
    Code_type INT AUTO_INCREMENT,
    Date_retour INT (10)
);
